// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWBl-Qw99Co2NnCPIUoBQ6GTAgbWpnXjg',
    appId: '1:1070698164567:web:027f8d9ff3cec30c1a0e12',
    messagingSenderId: '1070698164567',
    projectId: 'money-4jy4iq',
    authDomain: 'money-4jy4iq.firebaseapp.com',
    databaseURL: 'https://money-4jy4iq-default-rtdb.firebaseio.com',
    storageBucket: 'money-4jy4iq.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV-ln7QjjYMCPPGXr-6Os-wNr38QAsO2E',
    appId: '1:1070698164567:android:3e94ee72b4a4fa1a1a0e12',
    messagingSenderId: '1070698164567',
    projectId: 'money-4jy4iq',
    databaseURL: 'https://money-4jy4iq-default-rtdb.firebaseio.com',
    storageBucket: 'money-4jy4iq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4r2WAW3HLDg--oiu_fLc_rDYgzibtxuM',
    appId: '1:1070698164567:ios:a964b569f7a5ef731a0e12',
    messagingSenderId: '1070698164567',
    projectId: 'money-4jy4iq',
    databaseURL: 'https://money-4jy4iq-default-rtdb.firebaseio.com',
    storageBucket: 'money-4jy4iq.appspot.com',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4r2WAW3HLDg--oiu_fLc_rDYgzibtxuM',
    appId: '1:1070698164567:ios:2040fd09180eedb41a0e12',
    messagingSenderId: '1070698164567',
    projectId: 'money-4jy4iq',
    databaseURL: 'https://money-4jy4iq-default-rtdb.firebaseio.com',
    storageBucket: 'money-4jy4iq.appspot.com',
    iosBundleId: 'com.example.financeApp.RunnerTests',
  );
}
