// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqnEHi4oJhvKWs5fcu_SkiXfEW7ZBd4Sc',
    appId: '1:830014007940:web:3724a0714e03c0c87170d1',
    messagingSenderId: '830014007940',
    projectId: 'finance-manager-app-de5c1',
    authDomain: 'finance-manager-app-de5c1.firebaseapp.com',
    storageBucket: 'finance-manager-app-de5c1.appspot.com',
    measurementId: 'G-LJLQ2YRPNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-O9EVo6eGEeGSBK4Ei_nHaYMTNV8_buw',
    appId: '1:830014007940:android:ce7c1995fe8f23347170d1',
    messagingSenderId: '830014007940',
    projectId: 'finance-manager-app-de5c1',
    storageBucket: 'finance-manager-app-de5c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPuic_5No09fCMm_i7C-6mwSJvCRFTfws',
    appId: '1:830014007940:ios:30ac39959702e9147170d1',
    messagingSenderId: '830014007940',
    projectId: 'finance-manager-app-de5c1',
    storageBucket: 'finance-manager-app-de5c1.appspot.com',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPuic_5No09fCMm_i7C-6mwSJvCRFTfws',
    appId: '1:830014007940:ios:007f666a85c9c7de7170d1',
    messagingSenderId: '830014007940',
    projectId: 'finance-manager-app-de5c1',
    storageBucket: 'finance-manager-app-de5c1.appspot.com',
    iosBundleId: 'com.example.financeApp.RunnerTests',
  );
}
